name: Cypress Tests

on: 
  push:
  pull_request:
  schedule: 
    # every saturday at 01:00
    - cron: "0 1 * * 6"
    # daily at 03:00
    # - cron: "0 3 * * *"
  

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    # timeout-minutes: 150
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm install
          config: baseUrl=https://stabikat.de/search/
          spec: |
            cypress/e2e/spec.cy.js
            cypress/e2e/reviews.cy.js
            cypress/e2e/nested.cy.js
        #   browser: firefox
      # Lint Yaml
      - name: Yaml Lint
        run: npm run lint